project:
  type: book
  output-dir: docs

book:
  title: "Data Literacy for the Language Sciences"
  subtitle: "A very gentle introduction to statistics and data visualisation in R"
  author: 
  - name: Elen Le Foll
    orcid: 0000-0002-5839-8010
    email: elefoll@uni-koeln.de
  date: last-modified
  downloads: pdf
  license: "CC BY-NC-SA"
  sidebar:
    title: Data Literacy for the Language Sciences<br>(Le Foll 2024)
    tools:
      - icon: envelope
        href: mailto:elefoll@uni-koeln.de
  page-footer:
    background: light
    left: <a href="https://www.elenlefoll.eu">Elen Le Foll</a>
    center: <a href="https://benjamins.com/catalog/scl">Data Literacy for the Language Sciences</a>
    right: <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA</a>
  site-url: https://elenlefoll.github.io/RstatsTexbook/
  repo-url: https://github.com/elenlefoll/RstatsTextbook/
  repo-branch: main
  chapters:
    - index.qmd
    - OpenScholarship.qmd
    - references.qmd
  appendices:
    - FurtherResources.qmd

execute:
  message: false
  warning: false
  cache: true

bibliography: references.bib
csl: unified-style-sheet-for-linguistics.csl

lightbox: auto

format:
  html:
    theme: cosmo
    code-fold: true
    code-overflow: wrap
    code-tools: true
    code-link: false
    link-external-newwindow: true
    footnotes-hover: true
    author-meta: "Elen Le Foll"
  pdf:
    documentclass: scrreprt
    keep-tex: true
    include-in-header: 
       text: |
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
         \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}

