project:
  type: book
  output-dir: docs
book:
  title: Data Analysis for the Language Sciences
  subtitle: A very gentle introduction to statistics and data visualisation in `R`
  author:
  - name: Elen Le Foll
    orcid: 0000-0002-5839-8010
    email: elefoll@uni-koeln.de
  date: last-modified
  license: CC BY-NC-SA
  sidebar:
    title: Data Analysis for the<br>Language Sciences
    subtitle: Work in progress!
    tools:
    - icon: envelope
      href: mailto:elefoll@uni-koeln.de
  page-footer:
    background: light
    left: <a href="https://www.elenlefoll.eu">Elen Le Foll</a>
    center: Data Analysis for the Language Sciences
    right: <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA</a>
  site-url: https://elenlefoll.github.io/RstatsTexbook/
  repo-url: https://github.com/elenlefoll/RstatsTextbook/
  repo-branch: main
  chapters:
  - index.qmd
  - 1_OpenScholarship.qmd
  - 2_Data.qmd
  - 3_DataManagement.qmd
  - 4_InstallingR.qmd
  - 5_GettingStaRted.qmd
  - 6_ImpoRtingData.qmd
  - 7_VariablesFunctions.qmd
  - 8_DescriptiveStats.qmd
  - 9_DataWrangling.qmd
  - 10_Dataviz.qmd
  - 11_InferentialStats.qmd
  - 12_LinearRegression.qmd
  - 13_LiterateProgramming.qmd
  - 99_references.qmd
  - part: "Case studies"
    chapters: 
      - CS_Poppy.qmd
      - CS_RoseGina.qmd
  appendices:
    - A_FurtherResources.qmd

engine: knitr
execute:
  message: false
  warning: false
  cache: true
  freeze: auto
  out-width: "90%"
  fig-width: 6
  fig-asp: 0.618
bibliography: references.bib
csl: unified-style-sheet-for-linguistics.csl
lightbox: true

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: style.css
    code-fold: false # https://quarto.org/docs/output-formats/html-code.html
    code-line-numbers: false
    code-overflow: wrap
    code-tools: false
    code-link: false
    #dev: ragg_png
    dev: cairo
    #df-print: kable
    filters:
      - line-highlight
    link-external-newwindow: true
    footnotes-hover: true
    author-meta: Elen Le Foll
    
  # pdf:
  #   toc: true
  #   documentclass: scrreprt
  #   word-count: "{{< words-sum body-note >}}"
  #   keep-tex: true
  #   colorlinks: true
  #   prefer-html: true
  #   include-in-header:
  #      text: |
  #        \usepackage{fvextra}
  #        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
  #        \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}

