project:
  type: book
  output-dir: docs

book:
  title: "Data Literacy for the Language Sciences"
  #title: "Data Literacy for Language Research"
  #title: "Working with Quantitative Data in Language Research"
  subtitle: "A very gentle introduction to statistics and data visualisation in `R`"
  #description: "This is an in-progress Open Educational Resource developed by Dr. Elen Le Foll at the University of Cologne (Germany)."
  author: 
  - name: Elen Le Foll
    orcid: 0000-0002-5839-8010
    email: elefoll@uni-koeln.de
  date: last-modified
  #downloads: pdf
  license: "CC BY-NC-SA"
  sidebar:
    title: Data Literacy for the<br>Language Sciences
    subtitle: Work in progress!
    tools:
      - icon: envelope
        href: mailto:elefoll@uni-koeln.de
  page-footer:
    background: light
    left: <a href="https://www.elenlefoll.eu">Elen Le Foll</a>
    center: Data Literacy for the Language Sciences
    right: <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA</a>
  site-url: https://elenlefoll.github.io/RstatsTexbook/
  repo-url: https://github.com/elenlefoll/RstatsTextbook/
  repo-branch: main
  chapters:
    - index.qmd
    - OpenScholarship.qmd
    - DataManagement.qmd
    - InstallingR.qmd
    - GettingStaRted.qmd
    - references.qmd
  appendices:
    - FurtherResources.qmd

execute:
  message: false
  warning: false
  cache: true

bibliography: references.bib
csl: unified-style-sheet-for-linguistics.csl

lightbox: true

format:
  html:
    theme: cosmo
    code-fold: false # https://quarto.org/docs/output-formats/html-code.html
    code-line-numbers: false
    code-overflow: wrap
    code-tools: false # https://quarto.org/docs/output-formats/html-code.html
    code-link: false
    df-print: kable
    link-external-newwindow: true
    footnotes-hover: true
    author-meta: "Elen Le Foll"
  # pdf:
  #   toc: true
  #   documentclass: scrreprt
  #   word-count: "{{< words-sum body-note >}}"
  #   keep-tex: true
  #   colorlinks: true
  #   prefer-html: true
  #   include-in-header:
  #      text: |
  #        \usepackage{fvextra}
  #        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
  #        \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}

